version: '3.8'

services:
  # PHP Service
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    container_name: laravel_app
    volumes:
      - ./src:/var/www/html
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=laravel_db
      - MYSQL_USER=laravel_user
      - MYSQL_PASSWORD=laravel_secret
      - APP_ENV=local
      - APP_DEBUG=true
    depends_on:
      - mysql
    networks:
      - app_network

  # NGINX Service
  nginx:
    image: nginx:alpine
    container_name: nginx_server
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - app_network

  # MySQL Service
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_secret
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_secret
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

# Volumes for persistent data
volumes:
  mysql_data:

# Networks for communication between services
networks:
  app_network:
    driver: bridge
